name: Sync README

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour (adjust as needed)
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your own repository where the workflow is running
      - name: Checkout This Repo
        uses: actions/checkout@v3

      # Step 2: Check out the external repository where you want to copy the README from
      - name: Checkout External Repo
        uses: actions/checkout@v3
        with:
          repository: SimplifyJobs/Summer2025-Internships # Replace with the external repo details
          token: ${{ secrets.PAT_TOKEN }} # Use PAT to access the external repository
          path: external_repo

      # Step 3: Extract the desired portion of the README.md
      - name: Extract README.md Content
        run: |
          # Use sed to extract lines between the two patterns
          sed -n '/| Company | Role | Location | Application\/Link | Date Posted |/,/## We love our contributors ❤️❤️/p' external_repo/README.md | sed '$d' > README_temp.md

      # Step 4: Remove the specific image URL and Simplify link
      - name: Remove Image URL and Simplify Link
        run: |
          # Remove the specific image URL
          sed 's|https://i.imgur.com/u1KNU8z.png||g' README_temp.md > README_temp1.md
          # Remove any <a> tag containing the text "Simplify"
          sed '/<a[^>]*Simplify[^>]*>.*<\/a>/d' README_temp1.md > README.md

      # Step 5: Commit and push the changes to your own repository
      - name: Commit and Push Changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'actions@github.com'
          git add README.md
          git commit -m "Sync README from external_repo_name"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }} # Use PAT_TOKEN for pushing changes
