name: Sync README

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour (adjust as needed)
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your own repository where the workflow is running
      - name: Checkout This Repo
        uses: actions/checkout@v3

      # Step 2: Check out the first external repository (SimplifyJobs/Summer2025-Internships)
      - name: Checkout External Repo 1
        uses: actions/checkout@v3
        with:
          repository: SimplifyJobs/Summer2025-Internships
          token: ${{ secrets.PAT_TOKEN }}
          path: external_repo1

      # Step 3: Extract and Clean README.md Content from SimplifyJobs/Summer2025-Internships
      - name: Extract and Clean README.md Content from Repo 1
        run: |
          # Extract lines between the table start and the specific comment line in Repo 1
          sed -n '/| Company | Role | Location | Application\/Link | Date Posted |/,/<!-- Please leave a one line gap between this and the table TABLE_END (DO NOT CHANGE THIS LINE) -->/p' external_repo1/README.md | sed '$d' > README_part1_temp.md
          # Remove the specific image URL if present
          sed 's|https://i.imgur.com/u1KNU8z.png||g' README_part1_temp.md > README_part1.md
          # Debugging - Print README Part 1
          cat README_part1.md || echo "README_part1.md not created"

      # Step 4: Check out the second external repository (Ouckah/Summer2025-Internships)
      - name: Checkout External Repo 2
        uses: actions/checkout@v3
        with:
          repository: Ouckah/Summer2025-Internships
          token: ${{ secrets.PAT_TOKEN }}
          path: external_repo2

      # Step 5: Extract the desired portion of the README.md from Ouckah/Summer2025-Internships, excluding the header
      - name: Extract README.md Content from Repo 2 (Exclude Header)
        run: |
          # Extract rows excluding the header
          sed -n '/| Company | Role | Location | Application\/Link | Date Posted |/,/<!-- Please leave a one line gap between this and the table TABLE_END (DO NOT CHANGE THIS LINE) -->/p' external_repo2/README.md | sed '1d' | sed '$d' > README_part2.md
          # Debugging - Print README Part 2
          cat README_part2.md || echo "README_part2.md not created"

      # Step 6: Combine the extracted sections into a single README.md
      - name: Combine README Sections
        run: |
          {
            head -n 2 README_part1.md;
            tail -n +3 README_part1.md;
            cat README_part2.md;
          } > combined.md
          
          # Sort the combined content by the "Date Posted" column (column 5)
          sort -t '|' -k 5,5r combined.md > README.md || echo "Failed to combine and sort README sections"

      # Step 7: Clean up intermediate files
      - name: Clean Up
        run: |
          rm -f README_part1.md README_part1_temp.md README_part2.md combined.md
          rm -rf external_repo1 external_repo2

      # Step 8: Commit and push the changes to your own repository
      - name: Commit and Push Changes
        run: |
          git add README.md
          git commit -m "Sync README sections from SimplifyJobs and Ouckah Summer2025-Internships"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
