name: Sync README

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour (adjust as needed)
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your own repository where the workflow is running
      - name: Checkout This Repo
        uses: actions/checkout@v3

      # Step 2: Check out the first external repository (SimplifyJobs/Summer2025-Internships)
      - name: Checkout External Repo 1
        uses: actions/checkout@v3
        with:
          repository: SimplifyJobs/Summer2025-Internships
          token: ${{ secrets.PAT_TOKEN }}
          path: external_repo1

      # Step 3: Extract and Clean README.md Content from SimplifyJobs/Summer2025-Internships
      - name: Extract README.md Content from Repo 1
        run: |
          # Extract lines between the table start and the specific comment line in Repo 1
          sed -n '/| Company | Role | Location | Application\/Link | Date Posted |/,/<!-- Please leave a one line gap between this and the table TABLE_END (DO NOT CHANGE THIS LINE) -->/p' external_repo1/README.md | sed '$d' > README_part1.md
          # Remove the specific image URL if present
          sed -i 's|https://i.imgur.com/u1KNU8z.png||g' README_part1.md
          # Debugging - Print README Part 1
          cat README_part1.md || echo "README_part1.md not created"

      # Step 4: Check out the second external repository (Ouckah/Summer2025-Internships)
      - name: Checkout External Repo 2
        uses: actions/checkout@v3
        with:
          repository: Ouckah/Summer2025-Internships
          token: ${{ secrets.PAT_TOKEN }}
          path: external_repo2

      # Step 5: Extract README.md Content from Ouckah/Summer2025-Internships
      - name: Extract README.md Content from Repo 2
        run: |
          # Extract rows between the table start and the specific comment line
          sed -n '/| Company | Role | Location | Application\/Link | Date Posted |/,/<!-- Please leave a one line gap between this and the table TABLE_END (DO NOT CHANGE THIS LINE) -->/p' external_repo2/README.md | sed '1d;$d' > README_part2.md
          # Debugging - Print README Part 2
          cat README_part2.md || echo "README_part2.md not created"

      # Step 6: Combine the extracted sections into a single README.md
      - name: Combine README Sections
        run: |
          {
            cat README_part1.md;
            cat README_part2.md;
          } > README.md
          # Debugging - Print combined README.md
          cat README.md || echo "README.md not created"

      # Step 7: Commit and push the changes to your own repository
      - name: Commit and Push Changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'actions@github.com'
          git add README.md
          git commit -m "Sync README sections from SimplifyJobs and Ouckah Summer2025-Internships"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
