name: Sync README

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour (adjust as needed)
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your own repository where the workflow is running
      - name: Checkout This Repo
        uses: actions/checkout@v3

      # Step 2: Check out the external repository where you want to copy the README from
      - name: Checkout External Repo
        uses: actions/checkout@v3
        with:
          repository: SimplifyJobs/Summer2025-Internships # Replace with the external repo details
          token: ${{ secrets.PAT_TOKEN }} # Use PAT to access the external repository
          path: external_repo

      # Step 3: Copy the README.md from the external repository to your own repository
      - name: Copy README.md
        run: cp external_repo/README.md ./README.md

      # Step 4: Commit and push the changes to your own repository
      - name: Commit and Push Changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'actions@github.com'
          git add README.md
          git commit -m "Sync README from external_repo_name"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }} # Use PAT_TOKEN for pushing changes
