name: Sync README

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour (adjust as needed)
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your own repository where the workflow is running
      - name: Checkout This Repo
        uses: actions/checkout@v3

      # Step 2: Check out the first external repository (SimplifyJobs/Summer2025-Internships)
      - name: Checkout External Repo 1
        uses: actions/checkout@v3
        with:
          repository: SimplifyJobs/Summer2025-Internships
          token: ${{ secrets.PAT_TOKEN }} # Use PAT to access the first external repository
          path: external_repo1

      # Step 3: Extract the desired portion of the README.md from SimplifyJobs/Summer2025-Internships
      - name: Extract README.md Content from Repo 1
        run: |
          # Extract lines between the two patterns from Repo 1, excluding the unwanted section
          sed -n '/| Company | Role | Location | Application\/Link | Date Posted |/,/<!-- Please leave a one line gap between this and the table TABLE_END (DO NOT CHANGE THIS LINE) -->/p' external_repo1/README.md | sed '$d' | sed '/<!-- Please leave a one line gap between this and the table TABLE_END (DO NOT CHANGE THIS LINE) -->/d' > README_part1_temp.md
          # Debugging - Print README Part 1
          cat README_part1_temp.md || echo "README_part1_temp.md not created"

      # Step 4: Check out the second external repository (Ouckah/Summer2025-Internships)
      - name: Checkout External Repo 2
        uses: actions/checkout@v3
        with:
          repository: Ouckah/Summer2025-Internships
          token: ${{ secrets.PAT_TOKEN }} # Use PAT to access the second external repository
          path: external_repo2

      # Step 5: Extract the desired portion of the README.md from Ouckah/Summer2025-Internships
      - name: Extract README.md Content from Repo 2
        run: |
          # Extract lines between the table header and the specified comment line in Repo 2
          sed -n '/| Company | Role | Location | Application\/Link | Date Posted |/,/<!-- Please leave a one line gap between this and the table TABLE_END (DO NOT CHANGE THIS LINE) -->/p' external_repo2/README.md | sed '$d' > README_part2.md
          # Debugging - Print README Part 2
          cat README_part2.md || echo "README_part2.md not created"

      # Step 6: Combine the extracted sections into a single README.md
      - name: Combine README Sections
        run: |
          # Combine the README parts, remove duplicate headers and empty lines
          cat README_part1_temp.md README_part2.md | sed '/^| Company | Role | Location | Application\/Link | Date Posted |$/d' | sed '/^| ------- | ---- | -------- | ---------------- | ----------- |$/d' | sed '/^$/d' > README.md || echo "Failed to combine README sections"

      # Step 7: Commit and push the changes to your own repository
      - name: Commit and Push Changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'actions@github.com'
          git add README.md
          git commit -m "Sync README sections from SimplifyJobs and Ouckah Summer2025-Internships"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }} # Use PAT_TOKEN for pushing changes
